name: Continous Integration

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

env:
    PORT: 0
    MONGODB_URI: mongodb://localhost:27017
    DATABASE: necessity_test
    SESSION_SECRET: secret
    ACCESS_TOKEN_SECRET: access_secret
    ACCESS_TOKEN_EXPIRATION: 1h
    REFRESH_TOKEN_SECRET: refresh_secret
    REFRESH_TOKEN_EXPIRATION: 7d
    ISSUER: https://necessity.pro

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [15.x]
                mongodb-version: ['6.0']

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Use MongoDB ${{ matrix.mongodb-version }}
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - run: npm ci
            - run: npm run build --if-present
            - run: npm run ci

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
